version: '3.8'

services:
  app:
    build: .
    container_name: app-img
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules
    restart: always

  nginx:
    image: nginx:stable
    container_name: nginx-img
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./public:/usr/share/nginx/html/public
    depends_on:
      - app
    restart: always
