    version: '3.8'

    services:
      app:
        build: .
        container_name: app-img
        restart: unless-stopped
        networks:
          - app-network
        environment:
          - NODE_ENV=production
        expose:
          - "4000"  # Явно указываем экспортируемый порт

      nginx:
        image: nginx:latest
        container_name: nginx-img
        restart: unless-stopped
        ports:
          - "8080:8080"  # Внешний 8080 → внутренний 8080
        volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf
          - ./public:/usr/share/nginx/html/static  # Монтируем статику
        depends_on:
          - app
        networks:
          - app-network

    networks:
      app-network:
        driver: bridge